### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by b0g3r** [spbgti/it-workshop#4]
Докстринги по формату google style-guide, описывающие внутреннюю суть модуля/метода/класса. Типизация с помощью аннотаций и typing.

Документация API в виде описания эндпоинтов, посылаемых данных и структуры их ответов. Где - на твой выбор: на данном этапе можно просто в табличке в вики репозитория. Можно прикрутить swagger, но я бы, наверное, делал это потом.

**Comment by ishmuro** [comment]
Я бы сошёлся на формате докстрингов в виде [Google Python Style Guide](http://google.github.io/styleguide/pyguide.html) Для Sphinx есть дополнение, которое может их парсить -- [Napoleon](http://www.sphinx-doc.org/en/stable/ext/napoleon.html).

 Как по мне, намного более читаемые вещи получаются.

**Comment by b0g3r** [comment]
Как у них принято делать типизацию? Или юзаем аннотации + google docstrings?

**Comment by ishmuro** [comment]
Аннотации, полагаю. Насколько я знаю, они и используются

**Comment by b0g3r** [comment]
Ок, решено, отредактировал.
